apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: athena-control-plane-cert
  namespace: athena
spec:
  secretName: athena-control-plane-tls
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.athena.teamorchestrator.com
